output_dir = "/workspace/output"
dataset = "/workspace/diffusion-pipe/examples/dataset.toml"
epochs = 1000
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 4
gradient_clipping = 1
warmup_steps = 100
blocks_to_swap = 0
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1
save_every_n_epochs = 1
checkpoint_every_n_minutes = 5
activation_checkpointing = true
save_dtype = "bfloat16"
caching_batch_size = 1
video_clip_mode = "single_beginning"
partition_method = "parameters"
disable_block_swap_for_eval = false
eval_datasets = []

[model]
type = "wan"
ckpt_path = "/workspace"
dtype = "bfloat16"
timestep_sample_method = "logit_normal"
min_t = 0.875
max_t = 1
llm_path = "/workspace/models_t5_umt5-xxl-enc-bf16.pth"
transformer_path = "/workspace/high_noise_model"
transformer_dtype = "float8"

[adapter]
type = "lora"
rank = 64
dtype = "bfloat16"

[optimizer]
type = "adamw_optimi"
lr = 0.00002
betas = [ 0.9, 0.99,]
weight_decay = 0.01
eps = 1e-8
gradient_release = false
